### ISSUE TITLE
Xplora 4

### ISSUE THREAD

**Issue by Yankie69** [balmli/homey-smartpresence#12]
I connected my kids XPLORA 4 watches, all working good and Homey registering when the leave/arrive home (disconnect/connect to wifi), but I got an issue that the battery drain 4-5 times faster than normal when they now are connected at home.
I've been in contact with Xplora and they have checked and confirmed that my kids clocks drain the batteries much faster during the period I say they are connected to Homey/Smart Presence. They can not tell me why, but if you have any explanation/solution they were interested to bring it up with their software guys to try to make a fix. 
Any thoughts?

**Comment by okbangas** [comment]
My guess: You're checking presence way too often (standard is every 5 seconds). So the watch have traffic "constantly" on the network. Ask yourself: How fast do I have to know that they're at home, or have left. If it is within a minute or two, try to adjust settings for for the device to be checked every minute. My guess is it would reduce the battery drain.
