### ISSUE TITLE
Support for new type: Device (is_device)

### ISSUE THREAD

**Issue by okbangas** [balmli/homey-smartpresence#14]
#Smart presence is now used to tell whether someone is at home or not. If we could add is_device, it could be used to check if our kids are playing games (computer is on, PS4/5 is on etc) or doing schoolwork (school laptop is on). But, those units should NOT be used to indicate that someone is at home or not, someone left, someone arrived. However, triggers "devices turned on" and "device turned off" would be very welcome, telling that the device is turned on or off, as well as an state/condition "is online/is turned on".

If implemented, it could also be used for a wide variety of other cool scenarios, eg:

- When my office laptop is on during day, I'm working from home and the heating/light should take that into consideration.
- When the smart TV is turned on, the light shall be dimmed
- When the WiFi heater has lost network connection, issue a warning that heating may not be working.
- If the car was started (and thus logged on the wifi network) just after someone left the house, they are leaving by car.

**Comment by pjmpessers** [comment]
Would love that as well

**Comment by balmli** [comment]
You can try the very good Net Scan app for this.

https://homey.app/no-no/app/com.netscan/Net-Scan/
