### ISSUE TITLE
FR: Cards with number of people home 

### ISSUE THREAD

**Issue by matrover** [balmli/homey-smartpresence#16]
Hi, 

i really love this app (contributed to it actually). 
i have a feature request: i would really like the addition of cards which state how many people are home. or just an logic value that we can reference with the normal logic cards. 
 
use case (working from home):
```
IF desk is active (power measurement)
AND only 1 person is home
THEN: turn off the heating for the living room & turn on heating in office

IF desk is active (power measurement)
AND 2 or more persons are home
THEN: turn on heating in office
```

i now made an counter with logic, but it can be really usefull for a lot of use cases. 
ive examine your code to see if i can do this myself but i dont think so. 

Thanks for al your work and consideration of this feature.

**Comment by balmli** [comment]
Moved this to my Trello board. (but will still not promise if it till be fixed)

Will close issues tab in the github repo, so for further requests, use the community page: https://community.homey.app/t/app-pro-smart-presence/33794
