### ISSUE TITLE
[enhancement] BLE support ?

### ISSUE THREAD

**Issue by shaarkys** [balmli/homey-smartpresence#17]
Hi,
seeing https://github.com/athombv/homey-apps-sdk-issues/issues/81 closed in v6, would it be possible to get BLE support for Presence detection ? ;-) 

It would be great to detect eg. mobile, smart watches etc. .... eg. each user persona could be consisting out of : WiFi connection, BLE availability.... not sure if I'm not suggesting too much but it would be fantastic....

**Comment by balmli** [comment]
There are BLE devices / beacons that you can use.

With this app: https://homey.app/no-no/app/com.koktail.beacon/Beacon/
