### ISSUE TITLE
Bug makes device name not fully changeable, needs to be removed and recreated

### ISSUE THREAD

**Issue by jonatan1979** [balmli/homey-smartpresence#19]
If you change the name of a Smart Presence device, the old name persists internally (as can be seen in https://tools.developer.homey.app/tools/devices under Settings > `name`). The new name is shown as the current name in the normal UI (and the heading on the developer page), but the old name is the one that is used for the Who tag in flows. The old name is not editable, and there seems to be no way to fix this other than to remove these devices and recreate them with the new name (a work-around). This leads to confusion, and I doubt this is intended behavior. I haven't looked at the code, but I assume there are two different name properties internally, and only one is editable, but the other one is the one sent to flows.

Steps to reproduce:
1. Create smart presence device named _foo_.
2. Change name of smart presence device to _bar_.
3. Notice that the device is called _bar_ everywhere in the normal UI.
4. Notice that the device has a `name` property of _foo_ in the developer device list.
5. Create a test flow for this device with the tag Who logged somewhere, and note that _foo_ instead of _bar_ is used.

**Comment by balmli** [comment]
Will be fixed in 0.8.0
