### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Arjan-21** [balmli/homey-smartpresence#21]
Since the new update from yesterday the app stopped working after a few hours. Restart will help, but after a few hours got the same issue.

**Comment by balmli** [comment]
Thanks for reporting.

I'm looking at the problem, and will try to have a fix ready later today.

**Comment by Arjan-21** [comment]
Thanks for your quick response. 
Do you need some additional information?

**Comment by balmli** [comment]
No, thank you!

**Comment by Arjan-21** [comment]
Thanks.
I will test it and let you know.

**Comment by Arjan-21** [comment]
I think this is the solution!
Thank you for the quick response.
