### ISSUE TITLE
Incorrect Presence on iOS devices

### ISSUE THREAD

**Issue by MrBasque** [balmli/homey-smartpresence#25]
I have 4 IOS devices configured, all static Ip's. Worked flawlessly for a few years. 

Suddenly a few weeks ago the smart presence app started reporting random "away" triggers. Randomly for all devices separately. I assumed it had something to do with IOS or my netgear ORBI WiFi system, but I tested them with the Homey netgear app for state changes, but it does not report disconnects.

My away timeout is 600 and already tried d 900 without effect. iOS 15.3 does not fix anything either. Very annoying because I have a lot of flows depending on SP. 

Any suggestions or fixes for this?

**Comment by koendekort** [comment]
Some years ago I experienced the same problems with a script that I used to track the presence of smartphones (both android and ios) for Domoticz. The python script used a **ping** to find out if the device was present or not, but the device quite randomly reported 'not present' while actually 'present'. I changed the ping to an arping and found all my problems solved. No retries, no wait periods, no tricks but a straight forward answer: 'present' or 'not present'. Might this observation help making SmartPresence more reliable?
