### ISSUE TITLE
Not working on Homey FW  v7.4.0-rc.22

### ISSUE THREAD

**Issue by shaarkys** [balmli/homey-smartpresence#27]
Hi,
seems that detection doesn't work anymore on FW  v7.4.0-rc.22 :-( - no error, simply all devices are offline.

Diag. code 08c3244c-7f3d-495c-8f84-78f38834060f

**Comment by kgbengt** [comment]
I have the same problem.
f6b98ee0-60e8-44d4-8d3d-595d0cc2080e
Kalle Bengtsson

**Comment by balmli** [comment]
Hi,  Thank you for reporting !

Can you check v. 0.8.2 
https://homey.app/a/nl.terryhendrix.smartpresence/test/

and test a bit, please?


Best regards,
Bjørnar Almli

**Comment by kgbengt** [comment]
Installed, and seems to work! Will report if it doesn't. Thanks for the
swift reply and possible solution!

Den fre 15 apr. 2022 12:24Bjørnar Almli ***@***.***> skrev:

**Comment by copiis** [comment]
0.8.2 is working

**Comment by Askeo** [comment]
@balmli 
Same, use it for my PC and wifes PC, mine is connected and get tracked but the PC from my wife is constantly offline :/
