### ISSUE TITLE
All devices absent in homey after Update

### ISSUE THREAD

**Issue by Lars1234567888888888888888** [balmli/homey-smartpresence#28]
Hello

Homey updated to new version. Since then all devices frmerly working are now listed as absent, even when tey are up and running

**Comment by dbuekenh** [comment]
Same for me

**Comment by Askeo** [comment]
Same, use it for my PC and Wifes PC, mine is connected and get trackd but the PC from my wife is constantly offline :)

**Comment by Lars1234567888888888888888** [comment]
any update?
