### ISSUE TITLE
Still present - 8 minutes after i disconnected from WiFi

### ISSUE THREAD

**Issue by hummelmose** [balmli/homey-smartpresence#29]
![CleanShot 2022-07-25 at 16 08 25@2x](https://user-images.githubusercontent.com/8464889/180797276-2c3032b6-25e5-4e0f-8fc6-2f1ef5bfc2d7.png)

I want to switch from Unifi -> Smart Presence, but more than 8 minutes after I disconnected from the network Smart Presence still shows me as present. How often is it scanning the network ?

It took 18 minutes before it disconnected.

**Comment by Nutstree** [comment]
I ain't the owner of this project, but was going through the code to find the answer for this exact question. I then found out it is a setting which is configurable in the settings.

As far as I know, you have created at least 1 device which should be tracked by wifi. In the settings you will find something like: "away delay" which is default to 900sec (15min). This can be adjusted how you like.
<img width="548" alt="Screenshot 2023-05-29 at 13 57 28" src="https://github.com/balmli/homey-smartpresence/assets/4930420/f2d1d0ee-0c09-411c-9131-b97517e118e5">
