### ISSUE TITLE
Support a list or range of IP - addresses for one device

### ISSUE THREAD

**Issue by balmli** [balmli/homey-smartpresence#3]
If one of the devices in the list or range is present, then the device is present.

* A komma separated list of IP addresses, e.g. 192.168.1.10,192.168.1.20,192.168.1.30
* A range of IP addresses, e.g. 192.168.1.10-192.168.1.20

**Comment by rpb006** [comment]
In the new version thuis isn't working. Our is it a future wish?

**Comment by balmli** [comment]
No, this is an enhancement, not yet implemented.

**Comment by rpb006** [comment]
Thanks for reply, I can't wait for it. It will really help a lot of people.

**Comment by balmli** [comment]
This might lead to too high load on the Homey, so will not implement
