### ISSUE TITLE
Feature request: Presence last x hours

### ISSUE THREAD

**Issue by thomasekdahlN** [balmli/homey-smartpresence#33]
I have some needs that may be universal, because Homeys date handling in flows really suck, but I think smart presence can solve all my problems with som more functionality;-)

Adding a "**+/- hourr**" to every existing functionality. Like a "person has arrived the last $x hours" / "The last guest left last $z hours".

**This addition would give several advantages:**
- Building more stable flows (since some of my users are randomly on and of wifi without any real reason, instead of reporting the user has left the builing, adding a "has seen the user the last $x hours" would completely cure this problem.

- Heat planning (short term leave). When the last person was seen in the house 10hours or more ago, drop temperature in house like 1 degree (this setup would also ensure the normal day/night temperature work while people are at work/school so the house is not too cold while coming home. (At the moment I drop the temperature immediately all persons has left the house - which leeds to a colder house)

- Heat planning (long term leave). When the last person was seen in the house 24hours or more ago, drop temperature in house like 3 degrees.

Sure it would be other useful scenarios too.

Triggers
A household member arrived / left +/- hours ago
A kid (part of the household) arrived / left  +/- hours ago
A specific user arrived / left  +/- hours ago
A guest arrived / left  +/- hours ago
Someone arrived / left  +/- hours ago
The first household member arrived  +/- hours ago
The first kid arrived  +/- hours ago
The first guest arrived  +/- hours ago
The first person arrived  +/- hours ago
The last household member left  +/- hours ago
The last kid left  +/- hours ago
The last guest left  +/- hours ago
**The last person left  +/- hours ago** - Most important

Conditions
Household members home / No household members home   +/- hours ago
Kids at home / Kids not at home  +/- hours ago
Having guests / Not having guests  +/- hours ago
Someone is home / Nobody is home  +/- hours ago
**A specific user is home / away   +/- hours ago** - second most important

**Comment by balmli** [comment]
Moved this to my Trello board.   (but will still not promise if it till be fixed) 

For further requests, use the community page: https://community.homey.app/t/app-pro-smart-presence/33794
