### ISSUE TITLE
After updating to 0.8.2, when a person is absent, the device icon does not turn gray

### ISSUE THREAD

**Issue by kvacha13** [balmli/homey-smartpresence#36]
After updating to 0.8.2, on homey android application when a person is absent, the device icon does not turn gray. The actual status of the added device/person is updating/changing, but the icon does not gray out (on homey web application everything works OK).
![web](https://github.com/balmli/homey-smartpresence/assets/8162633/621151bf-98b7-422e-a903-a22aad42770c)
![android](https://github.com/balmli/homey-smartpresence/assets/8162633/26c4331c-76df-49e4-b20a-13c3b916e759)

**Comment by 2tracer** [comment]
I have the exact same problem.
Now all house is on full power all the time.

**Comment by ries1971** [comment]
Me to

**Comment by kvacha13** [comment]
in addition, "Last person left" triggers falsely.  In general, the new version is not working as supposed. Wanted to roll back to the previous version but the releases are not available (strange). Seems I have to look for the alternative.

**Comment by nisseo** [comment]
Same problem with icon for me too. 😪

**Comment by balmli** [comment]
Is this from the new iOS app ?   If so, it's an issue for Athom.  They have been contacted.

It is still working in the Web UI
