### ISSUE TITLE
Tag in the AND section not working

### ISSUE THREAD

**Issue by Eternity-again** [balmli/homey-smartpresence#4]
If I use the card 'a household member' came in (or left) and use a TAG in the AND section with a logical card, it still reports ALL members home (or away).
<img width="884" alt="Schermafbeelding 2020-08-24 om 17 33 56" src="https://user-images.githubusercontent.com/10754229/91065163-712fd400-e630-11ea-9a27-bc44a611dbb5.png">

**Comment by balmli** [comment]
First: what version do you use?   The latest 0.6.1 can be installed: https://homey.app/a/nl.terryhendrix.smartpresence/test/

The "Someone arrived" (Iemand kwam binnen) - trigger sets the name of the device (who / wie) as a token, and will trigger every time a person arrives.
