### ISSUE TITLE
Missing Tag in flow card

### ISSUE THREAD

**Issue by hbeers** [balmli/homey-smartpresence#5]
When using Smart Presence (0.6.1) in a flow it reports a missing tag ...
(When user comes in....) ...

![image](https://user-images.githubusercontent.com/21137344/91446374-b134c800-e877-11ea-9d84-d8af2939cec8.png)

This did not occur in previous version ....

**Comment by balmli** [comment]
Hi,  Thank you for reporting.

Yes, I see that the old version had a token with the name.  The "User entered" (Gebruiker kwam binnen) is for the selected user.  In this case "Henny", and the token will always return "Henny".

I will add the token, so it works as the previous version (0.5.0 / 0.5.1).

**Comment by balmli** [comment]
Fixed in v. 0.6.2

**Comment by hbeers** [comment]
Great work Bjørnar !!!

And many thanks for picking up the good work.
____________________________________________________________

Henny van Beers
Pelgrimshei 92
5685 HT, Best
+31 6 47924189


Op do 27 aug. 2020 om 17:46 schreef Bjørnar Almli <notifications@github.com
