### ISSUE TITLE
Possible to check computer?

### ISSUE THREAD

**Issue by pjmpessers** [balmli/homey-smartpresence#6]
I have a HTPC with a DVB-C tv tuner and media center installed for recording my TV-recordings. About ones a week this PC crashes. So i have a wifi switch that power down and power up this PC and the PC starts to reboot and continue the recording. But for it to work it needs te see in the network of this PC is down. I wanted to use smart precense for that.
It can detect my smartphone. That is great. But it won't see my PC.

Can that be included?

**Comment by balmli** [comment]
Hi, 

I will add support to set the port - number from Advanced settings, in the next version of the app.  So you should be able to detect the PC.

**Comment by pjmpessers** [comment]
That would be great. Thank you.

**Comment by pjmpessers** [comment]
It works great. Thank you. Just what i needed.

**Comment by balmli** [comment]
So it works as expected on v. 0.6.3 ?

**Comment by pjmpessers** [comment]
No. I sideloaded v0.7.0 with npm.

**Comment by balmli** [comment]
Yeah !! Cool,  thanks for the info. 

Can I ask which port number you use for the PC ?

Will release 0.7.0 when more language support is ready

**Comment by pjmpessers** [comment]
I'm using port 1028. I was using this port because netscan only worked on this port. But that app isn't working on v5 and i think the developer stopped supporting this app.

I needed to open this port in the firewall of windows to make it work.
