### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by topkock** [balmli/homey-smartpresence#7]
Always worked great. Stopped working somewhere today. Seems there was an update today?
People home are not recognised anymore (ip unchanged).
And cannot make flow argument with specific person anymore..?
Thanks for any feedback.

**Comment by balmli** [comment]
This issue have been fixed, but not yet released by Athom yet. 

But you can install v.0.6.3 from test:

https://homey.app/a/nl.terryhendrix.smartpresence/test/

**Comment by topkock** [comment]
Thanks!
That does seem to resolve it.
However I did notice that I cannot make an AND flow like before( has been some time since I checked).
A specific person being present...
See below with user ‘ Li’.
I only get 3 options now and this is not one of it...
Thanks,
Niels

[cid:9312C1B3-5C75-42E4-88C5-09C403239F2A]

Op 31 aug. 2020 om 20:31 heeft Bjørnar Almli <notifications@github.com> het volgende geschreven:

﻿

This issue have been fixed, but not yet released by Athom yet.

But you can install v.0.6.3 from test:

https://homey.app/a/nl.terryhendrix.smartpresence/test/
