### ISSUE TITLE
Presence not working after update

### ISSUE THREAD

**Issue by burnis** [balmli/homey-smartpresence#8]
Presence doesn’t work after update 0.6.2 on Homey 4.2.0.

Tried to remove users and add again but still not working.

**Comment by balmli** [comment]
Hi,

This has been fixed in v. 0.6.3, which can be installed from this link:

https://homey.app/a/nl.terryhendrix.smartpresence/test/

**Comment by burnis** [comment]
Thank you! Works perfect now 😀
