### ISSUE TITLE
Homey very slow after update 0.6.2

### ISSUE THREAD

**Issue by avanderwulp** [balmli/homey-smartpresence#9]
My Homey is very slow after the update of Smartpresence 0.6.2. My Homey is an early 2018 with software 4.2.0.
I removed the app from my Homey and everything was normal again. When I put the app back on Homey it is again very slow.
What is wrong ?

**Comment by balmli** [comment]
Do you have many devices installed?

You can try to increase the "Normal mode check interval" and also the "Stress mode check interval".

Try 3000 and 1000, and see if that helps

**Comment by avanderwulp** [comment]
Do you mean devices in the Smartpresence app ? Normally four, this afternoon after re-installing the app only one.

⁣BlueMail voor Android downloaden ​

Op 1 sep. 2020 19:39, om 19:39, "Bjørnar Almli" <notifications@github.com> schreef:

**Comment by balmli** [comment]
Yes. 

Try changing the settings, and see if that helps

**Comment by avanderwulp** [comment]
Good morning,

I changed the settings as you said. Homey is now a bit faster as with the standard settings but not as fast as it must be.

Greetings,

Arjan

⁣BlueMail voor Android downloaden ​

Op 1 sep. 2020 21:40, om 21:40, "Bjørnar Almli" <notifications@github.com> schreef:

**Comment by balmli** [comment]
OK,

you can try to increase the settings further, and see if it improves

**Comment by balmli** [comment]
Can you check the app from the profiling page?

Open this URL, as select "nl.terryhendrik.smartpresence":

https://developer.athom.com/tools/app-profiling

You can also open https://insights.homey.app/  and look at "Smart Presence - CPU"

**Comment by avanderwulp** [comment]
This is a screenshot from the CPU page .

Arjan

⁣BlueMail voor Android downloaden ​

Op 2 sep. 2020 11:50, om 11:50, "Bjørnar Almli" <notifications@github.com> schreef:

**Comment by balmli** [comment]
Sorry, I can't see any screenshot

**Comment by avanderwulp** [comment]
![Screenshot_20200902-120529](https://user-images.githubusercontent.com/70590910/91977526-17f82c80-ed23-11ea-8004-77a1b2bf5d50.png)

**Comment by avanderwulp** [comment]
Don't know if you see anything, I don't 🙄

**Comment by avanderwulp** [comment]
![Screenshot_20200902-135119](https://user-images.githubusercontent.com/70590910/91977784-73c2b580-ed23-11ea-96ce-6f8f083469ff.png)

**Comment by balmli** [comment]
No, it's not easy on the phone.

**Comment by balmli** [comment]
People report to me that setting "Normal mode check interval" to 5000 and "Stress mode check interval" to 2500 works better.

**Comment by avanderwulp** [comment]
![Screenshot_20200902-135119](https://user-images.githubusercontent.com/70590910/91986815-7fb37500-ed2d-11ea-9917-be9edfef8bed.png)
![Screenshot_20200902-120529](https://user-images.githubusercontent.com/70590910/91986820-80e4a200-ed2d-11ea-873b-1c3e8a335599.png)

**Comment by avanderwulp** [comment]
![IMG_20200902_150143226](https://user-images.githubusercontent.com/70590910/91986952-aa053280-ed2d-11ea-9474-87e7923f381c.jpg)
![Uploading IMG_20200902_150244806.jpg…]()

**Comment by balmli** [comment]
Have you tested v. 0.7.2 ?

**Comment by avanderwulp** [comment]
Yes I have tested it. I have  set Normal mode check interval" to 10000 and "Stress mode check interval" to 5000 . Now Homey is back to normal speed. Although I yesterday get a few notifications : first of family at home when three persons were at home and nobody was coming home.

**Comment by balmli** [comment]
OK, thanks
